### ISSUE TITLE
textarea TODO

### ISSUE THREAD

**Issue by lunixbochs** [talonvoice/talon#254]
- [ ] optimize relayout: split line wrapping from vertical layout recalculation, and only do line wrapping on lines that are directly modified (dirty) or the whole view (if the effective view width or font size changes), but do vertical recalculation after a point, anytime the number of lines changes
- [ ] word level selection (e.g. alt-left) doesn't stop at newlines
- [ ] newlines are rendered, in a kind of weird way. they interact strangely with selection and rendering.
- [ ] the undo stack isn't cleared when you set .value, so if you reuse a textarea for a while, it will have stale undo info that doesn't make sense anymore
- [ ] some bugs

hotkeys:
- [ ] missing some hotkeys (e.g. shift-delete, generally other modifier-delete)

scrolling:
- [ ] viewport doesn't auto scroll as you type
- [ ] viewport doesn't auto scroll as you click+drag
- [ ] no viewport culling (this means large text will be slow)
- [ ] no viewport query API yet (viewport extent + visible region)
- [ ] doesn't update labels and highlights on scroll until you move your mouse
- [ ] no scrollbar yet

**Comment by splondike** [comment]
Some potential UX improvements:

- [ ] If you have this text: "This is% my *text that wrap\nThis is a new line". The * is the wrap position of the first line, the % is the caret. If you press down, the position goes onto "This is a new line" rather than into "text that wrap".
- [ ] Triple click selects a whole line of text in most text widgets, but not this one.
- [ ] Shift+Insert and middle click both paste from the linux selection clipboard in many text widgets, but not this one.
- [ ] Only difference when the window is focussed is the caret blinking. Could have a title bar colour change property for example.
- [x] Textarea doesn't work if you don't set a value then show it. It should probably default to the empty string as its value.
- [ ] If you have a wrap at '\*' and click at '$' the cursor goes to "Another line" rather than the end of "wraps":
Some line that\*
wraps    $
Another one

**Comment by lunixbochs** [comment]
Thanks! I skipped triple click for now because there's no native support for it in Qt, so I'm going to add it to my Canvas layer before it ends up in TextArea.

**Comment by rntz** [comment]
The behavior of undo in text areas is character-by-character, which makes undoing any significant amount of work very tedious.

**Comment by knausj85** [comment]
This user.paste function:
https://github.com/knausj85/knausj_talon/blob/master/code/edit.py#L21

simply doesn't work on Mac when the draft window has focus. The previous contents of the clipboard appears, no matter how large the delay. 

simple test case:
```
stupid test: user.paste("WHATEVER")
```

**Comment by timo** [comment]
* some visual indicator for continuation lines to differentiate between hard- and soft-wrapped lines  
* low-priority, maybe an API to allow putting stuff (labels / icons / buttons) in a gutter / ruler on the left, maybe on an extra gutter on the right (this would likely also include support for line numbers)

**Comment by splondike** [comment]
- [ ] Spans can't be compared for functional equality. I.e. Span(1, 1) == Span(1, 1) returns False.

**Comment by nriley** [comment]
I wasn't able to reproduce the issue in https://github.com/talonvoice/talon/issues/254#issuecomment-789355238.

- [ ] Mouse cursor is not set properly

Is there any thought about using normal window chrome so you'd get OS behavior (e.g. resizing, standard indication of focus) or does it make more sense to continue to implement these individually?

**Comment by SCdF** [comment]
In case not many people use windows draft submit doesn't work correctly, missing the first piece of text, presumably due to a timeout issue.

If I try to submit the sentence above (into this window), draft submit doesn't paste the "In case".
