### ISSUE TITLE
Native Screen Tracking

### ISSUE THREAD

**Issue by lunixbochs** [talonvoice/talon#382]
This is an issue to track replacing Qt's screen tracking with a more reliable cross-platform solution.

- [x] Windows
  - [x] screen/layout/resolution changes
    - https://stackoverflow.com/a/33762334/293352
    - EnumDisplayMonitors: https://stackoverflow.com/a/26541793/293352
  - [x] reserved space changes
    - https://github.com/talonvoice/talon/issues/156
  - [ ] TODO: DPI changes?
    - https://docs.microsoft.com/en-us/windows/win32/hidpi/wm-dpichanged - NOTE: this seems to require you to have a window on each monitor?
    - looks like DPI changes trigger WM_DISPLAYCHANGE as well
- [x] macOS
  - [x] screen changes (includes DPI)
    - https://github.com/talonvoice/talon/issues/248
    - https://github.com/talonvoice/talon/issues/278
    - https://github.com/talonvoice/talon/issues/303
  - [x] reserved space changes
    - https://github.com/talonvoice/talon/issues/381
- [x] Linux
  - [x] screen changes
    - https://github.com/pjvds/xrandr-notify/blob/master/main.go
    - https://github.com/talonvoice/talon/issues/218
  - [x] reserved space changes
    - https://github.com/talonvoice/talon/issues/285#issuecomment-886003769
    - (this is waiting on more `xprop -root` output from users)
  - [ ] TODO: DPI changes? no idea yet what the linux hidpi apis look like
    - https://unix.stackexchange.com/questions/596765/is-x-dpi-dot-per-inch-setting-just-meant-for-text-scaling
